name: Terraform Client App Deploy

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "App name to deploy (must exist in apps.json)"
        required: true
        type: string
      branch:
        description: "Select branch/environment"
        required: true
        type: choice
        options:
          - develop
          - staging
          - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    defaults:
      run:
        working-directory: Client-App/terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: ${{ vars.REGION }}
      TF_VAR_short_region: ${{ vars.SHORT_REGION }}
      TF_VAR_env: ${{ vars.ENV }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set environment mapping
        id: set-env
        run: |
          if [ "${{ github.event.inputs.branch }}" == "develop" ]; then
            echo "env=dev" >> $GITHUB_OUTPUT
            echo "TF_VAR_env=dev" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.branch }}" == "staging" ]; then
            echo "env=stg" >> $GITHUB_OUTPUT
            echo "TF_VAR_env=stg" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.branch }}" == "main" ]; then
            echo "env=prod" >> $GITHUB_OUTPUT
            echo "TF_VAR_env=prod" >> $GITHUB_ENV
          else
            echo "Unknown branch"; exit 1
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TF_VAR_region }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Validate App Name from apps.json
        working-directory: .
        run: |
          APP_NAME="${{ github.event.inputs.app_name }}"
          if ! jq -e ".[] | select(.name == \"$APP_NAME\")" apps.json > /dev/null; then
            echo "❌ Error: App '$APP_NAME' not found in apps.json"
            exit 1
          fi
          echo "✅ App '$APP_NAME' found in apps.json"

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=s3-ulng-clientapps-tfstate" \
            -backend-config="key=cognito-app-clients/$TF_VAR_env/${{ github.event.inputs.app_name }}/terraform.tfstate" \
            -backend-config="region=$TF_VAR_region"

      - name: Terraform Plan
        run: |
          terraform plan \
            -var="env=$TF_VAR_env" \
            -var="region=$TF_VAR_region" \
            -var="app_name=${{ github.event.inputs.app_name }}" \
            -out=plan.tfout

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.tfout
