name: Terraform Deploy

on:
  push:
    branches:
      - develop
      - staging
      - production

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    defaults:
      run:
        working-directory: terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_region: ${{ vars.REGION }}
      TF_VAR_short_region: ${{ vars.SHORT_REGION }}

    steps:
    - uses: actions/checkout@v4

    - name: Upgrade AWS CLI v2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install --update
        /usr/local/bin/aws --version

    - name: Determine Environment from Branch
      id: set-env
      run: |
        BRANCH=$(git rev-parse --abbrev-ref HEAD)
        case $BRANCH in
          develop) echo "TF_VAR_env=dev" >> $GITHUB_ENV ;;
          staging) echo "TF_VAR_env=stg" >> $GITHUB_ENV ;;
          main) echo "TF_VAR_env=prod" >> $GITHUB_ENV ;;
          *) echo "Unsupported branch: $BRANCH"; exit 1 ;;
        esac
        echo "Environment set to: $TF_VAR_env"

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=terraform-state-test-cognito" \
          -backend-config="key=cognito-app-clients/$TF_VAR_env/terraform.tfstate" \
          -backend-config="region=$TF_VAR_region"

    - name: Terraform Plan
      run: |
        terraform plan \
          -var="env=$TF_VAR_env" \
          -var="region=$TF_VAR_region" \
          -out=plan.tfout

    - name: Terraform Apply
      run: terraform apply -auto-approve plan.tfout
